services:
  - type: web
    name: editvideo
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WHISPER_MODEL
        value: tiny
      - key: WHISPER_LANGUAGE
        value: it
